// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import RingTimerController from "./ring_timer_controller"
application.register("ring-timer", RingTimerController)

import CelebrationController from "./celebration_controller"
application.register("celebration", CelebrationController)

import TimerBadgeController from "./timer_badge_controller"
application.register("timer-badge", TimerBadgeController)

import TimerClearController from "./timer_clear_controller"
application.register("timer-clear", TimerClearController)
